const projects = [
  {
    id: 1,
    title: "accordion",
    category: "react",
    img: "./images/accordion.png",
    desc: `accordion (collapsible content).`,
    gitLink: "https://github.com/ZoranUTF8/Acordion-react",
    liveApp: "https://accordion-ex.netlify.app",
  },
  {
    id: 2,
    title: "checkout cart",
    category: "react",
    img: "./images/checkout-cart.png",
    desc: `online shopping cart.`,
    gitLink: "https://github.com/ZoranUTF8/cartCheckout",
    liveApp: "https://cartcheckout.netlify.app",
  },
  {
    id: 3,
    title: "cocktails search",
    category: "react",
    img: "./images/cocktails-api.png",
    desc: `cocktails API integration.`,
    gitLink: "https://github.com/ZoranUTF8/cocktailsList",
    liveApp: "https://yourcocktails.netlify.app",
  },
  {
    id: 4,
    title: "color shades",
    category: "react",
    img: "./images/color-shade.png",
    desc: `css color shades.`,
    gitLink: "https://github.com/ZoranUTF8/colorShades",
    liveApp: "https://color-shades-gen.netlify.app",
  },
  {
    id: 5,
    title: "restaurant menu",
    category: "react",
    img: "./images/foodmenu.png",
    desc: `restaurant menu.`,
    gitLink: "https://github.com/ZoranUTF8/food-menu",
    liveApp: "https://food-menu-ex.netlify.app",
  },
  {
    id: 6,
    title: "grocery memo list",
    category: "react",
    img: "./images/grocery-reminder.png",
    desc: `grocery memo.`,
    gitLink: "https://github.com/ZoranUTF8/grocery-list",
    liveApp: "https://grocery-memo.netlify.app",
  },
  {
    id: 7,
    title: "html markdown",
    category: "react",
    img: "./images/html-markdown.png",
    desc: `html markdown.`,
    gitLink: "https://github.com/ZoranUTF8/HTML_markdown_preview",
    liveApp: "https://htmlmarkdown.netlify.app",
  },
  {
    id: 8,
    title: "Library",
    category: "java",
    img: "./images/java-library.png",
    desc: `console library app.`,
    gitLink: "to do",
    liveApp: "to do",
  },
  {
    id: 9,
    title: "lorem generator",
    category: "react",
    img: "./images/lorem.png",
    desc: `lorem ipsum generator.`,
    gitLink: "https://github.com/ZoranUTF8/lorem_ipsum_generator",
    liveApp: "https://loremgenerator01.netlify.app",
  },
  {
    id: 10,
    title: "modal & sidebar",
    category: "react",
    img: "./images/modal-sidebar.png",
    desc: `modal sidebar example.`,
    gitLink: "https://github.com/ZoranUTF8/modalAndSidebar",
    liveApp: "https://modal-sidebar-ex.netlify.app",
  },
  {
    id: 11,
    title: "navbar",
    category: "react",
    img: "./images/navbar.png",
    desc: `responsive navbar.`,
    gitLink: "https://github.com/ZoranUTF8/navbar",
    liveApp: "https://navbar-ex.netlify.app",
  },
  {
    id: 12,
    title: "user pagination",
    category: "react",
    img: "./images/pagination.png",
    desc: `pagination example.`,
    gitLink: "https://github.com/ZoranUTF8/githubFollowers",
    liveApp: "https://git-followers.netlify.app",
  },
  {
    id: 13,
    title: "photo search",
    category: "react",
    img: "./images/photo-search.png",
    desc: `photo search.`,
    gitLink: "https://github.com/ZoranUTF8/photoScroll",
    liveApp: "https://infinitephotoscroll.netlify.app",
  },
  {
    id: 14,
    title: "random person ",
    category: "react",
    img: "./images/random-person.png",
    desc: `random person generator.`,
    gitLink: "https://github.com/ZoranUTF8/randomPerson",
    liveApp: "https://app.netlify.com/sites/randompersoninfo/settings/general",
  },
  {
    id: 15,
    title: "review",
    category: "react",
    img: "./images/review.png",
    desc: `review example.`,
    gitLink: "https://github.com/ZoranUTF8/Reviews",
    liveApp: "https://reviews-ex.netlify.app",
  },
  {
    id: 16,
    title: "slider",
    category: "react",
    img: "./images/slider.png",
    desc: `slider example.`,
    gitLink: "https://github.com/ZoranUTF8/Slider-react",
    liveApp: "https://slider-ex.netlify.app",
  },
  {
    id: 17,
    title: "stripe",
    category: "react",
    img: "./images/stripe-clone.png",
    desc: `stripe clone.`,
    gitLink: "https://github.com/ZoranUTF8/stripe-clone",
    liveApp: "https://stripe-clonereact.netlify.app",
  },
  {
    id: 18,
    title: "tabs",
    category: "react",
    img: "./images/tabs.png",
    desc: `tabs example.`,
    gitLink: "https://github.com/ZoranUTF8/Tabs-react",
    liveApp: "https://tabs-ex.netlify.app",
  },
  {
    id: 19,
    title: "theme",
    category: "react",
    img: "./images/toggle-theme.png",
    desc: `toggle theme.`,
    gitLink: "https://github.com/ZoranUTF8/toggleTheme",
    liveApp: "https://toggle-darklight-theme.netlify.app",
  },
  {
    id: 20,
    title: "tours",
    category: "react",
    img: "./images/tours-sale.png",
    desc: `tours sale.`,
    gitLink: "https://github.com/ZoranUTF8/tours-sale-react",
    liveApp: "https://tours-sale.netlify.app",
  },
  {
    id: 21,
    title: "hacker news",
    category: "react",
    img: "./images/hacker-news.png",
    desc: `hacker news api.`,
    gitLink: "https://github.com/ZoranUTF8/hacker_news_react_API",
    liveApp: "https://hacker-news-react-api.netlify.app",
  },
  {
    id: 22,
    title: "movie search",
    category: "react",
    img: "./images/movie-search.png",
    desc: `movie search api.`,
    gitLink: "https://github.com/ZoranUTF8/movieDB_react",
    liveApp: "https://search-moviedb-react.netlify.app",
  },
  {
    id: 23,
    title: "Yelp camp",
    category: "node",
    img: "./images/yelpcamp.png",
    desc: `Yelp camp clone.`,
    gitLink: "https://github.com/ZoranUTF8/yelpCampClone",
    liveApp: "https://boiling-basin-15012.herokuapp.com",
  },
  {
    id: 24,
    title: "Task manager",
    category: "node",
    img: "./images/task-manager.png",
    desc: `Task manager.`,
    gitLink: "https://github.com/ZoranUTF8/taskManager",
    liveApp: "https://desolate-taiga-35155.herokuapp.com/",
  },
  {
    id: 25,
    title: "Online blog",
    category: "node",
    img: "./images/online-blog.png",
    desc: `Personal blog app.`,
    gitLink: "https://github.com/ZoranUTF8/PersonalBlogApp",
    liveApp: "https://fathomless-citadel-04850.herokuapp.com",
  },
  {
    id: 26,
    title: "Personal website",
    category: "static",
    img: "./images/sokoun.png",
    desc: `art gallery website.`,
    gitLink: "https://github.com/ZoranUTF8/Sokoun_art_gallery",
    liveApp: "https://zoranutf8.github.io/Sokoun_art_gallery",
  },
  {
    id: 27,
    title: "Task manager",
    category: "react",
    img: "./images/taskm.png",
    desc: `Task manager.`,
    gitLink: "https://github.com/ZoranUTF8/Keeper_react.js",
    liveApp: "https://desolate-taiga-35155.herokuapp.com",
  },
   {
    id: 28,
    title: "Weather forecast",
    category: "node",
    img: "./images/weather.png",
    desc: `Weather forecast.`,
    gitLink: "https://github.com/ZoranUTF8/WeatherApi",
    liveApp: "https://mighty-brushlands-35689.herokuapp.com",
  },
  {
    id: 29,
    title: "Fabrika ukusa",
    category: "static",
    img: "./images/fabrikaukusa.png",
    desc: `Restaurant website.`,
    gitLink: "https://github.com/ZoranUTF8/fabrika_ukusa_webPage",
    liveApp: "https://zoranutf8.github.io/fabrika_ukusa_webPage/",
  },
  {
    id: 30,
    title: "Photo blog",
    category: "static",
    img: "./images/photoblog.png",
    desc: `Restaurant website.`,
    gitLink: "https://github.com/ZoranUTF8/Photo_blog",
    liveApp: "https://zoranutf8.github.io/Photo_blog/",
  },
  {
    id: 31,
    title: "Pricing panel",
    category: "static",
    img: "./images/ppanel.png",
    desc: `Pricing panel example.`,
    gitLink: "https://github.com/ZoranUTF8/pricingPanel",
    liveApp: "https://zoranutf8.github.io/pricingPanel/",
  },
  {
    id: 32,
    title: "Sales panel",
    category: "java",
    img: "./images/internetsales.png",
    desc: `Internet package sales panel.`,
    gitLink: "https://github.com/ZoranUTF8/Internet-Package-App",
    liveApp: "https://zoranutf8.github.io/pricingPanel/",
  },
  {
    id: 33,
    title: "Tinder copy",
    category: "static",
    img: "./images/tinderdog.png",
    desc: `Tinder website copy.`,
    gitLink: "https://github.com/ZoranUTF8/ThunderDogSample",
    liveApp: "https://zoranutf8.github.io/ThunderDogSample/",
  },
  {
    id: 34,
    title: "Candy museum",
    category: "static",
    img: "./images/candy.png",
    desc: `Museum of candy website.`,
    gitLink: "https://github.com/ZoranUTF8/Museum_Of_Candy_Project",
    liveApp: "https://zoranutf8.github.io/Museum_Of_Candy_Project/",
  },
  {
    id: 35,
    title: "Job posting api",
    category: "Api",
    img: "./images/jobapi.png",
    desc: `API with JSON Web Token auth.`,
    gitLink: "https://github.com/ZoranUTF8/Jobs_API",
    liveApp: "https://jobs-api-zoran.herokuapp.com/api-docs/",
  },
  {
    id: 36,
    title: "Inventory api",
    category: "Api",
    img: "./images/inventory.png",
    desc: `API with CRUD/sorting operations..`,
    gitLink: "https://github.com/ZoranUTF8/store_API/tree/main",
    liveApp: "https://jobs-api-zoran.herokuapp.com/api-docs/",
  },
  {
    id: 37,
    title: "Quiz",
    category: "react",
    img: "./images/react-quiz.png",
    desc: `React quiz`,
    gitLink: "https://github.com/ZoranUTF8/react-quiz",
    liveApp: "https://react-quizdb.netlify.app",
  },
 
]

export default projects;
