const projects = [
  {
    id: 1,
    title: "accordion",
    category: "react",
    img: "./images/accordion.png",
    desc: `accordion (collapsible content).`,
  },
  {
    id: 2,
    title: "checkout cart",
    category: "react",
    img: "./images/checkout-cart.png",
    desc: `online shopping cart.`,
  },
  {
    id: 3,
    title: "cocktails search",
    category: "react",
    img: "./images/cocktails-api.png",
    desc: `cocktails API integration.`,
  },
  {
    id: 4,
    title: "color shades",
    category: "react",
    img: "./images/color-shade.png",
    desc: `css color shades.`,
  },
  {
    id: 5,
    title: "restaurant menu",
    category: "react",
    img: "./images/foodmenu.png",
    desc: `restaurant menu.`,
  },
  {
    id: 6,
    title: "grocery memo list",
    category: "react",
    img: "./images/grocery-reminder.png",
    desc: `grocery memo.`,
  },
  {
    id: 7,
    title: "html markdown",
    category: "react",
    img: "./images/html-markdown.png",
    desc: `html markdown.`,
  },
  {
    id: 8,
    title: "Library",
    category: "java",
    img: "./images/java-library.png",
    desc: `console library app.`,
  },
  {
    id: 9,
    title: "lorem generator",
    category: "react",
    img: "./images/lorem.png",
    desc: `lorem ipsum generator.`,
  },
  {
    id: 10,
    title: "modal & sidebar",
    category: "react",
    img: "./images/modal-sidebar.png",
    desc: `modal sidebar example.`,
  },
  {
    id: 11,
    title: "navbar",
    category: "react",
    img: "./images/navbar.png",
    desc: `responsive navbar.`,
  },
  {
    id: 12,
    title: "user pagination",
    category: "react",
    img: "./images/pagination.png",
    desc: `pagination example.`,
  },
  {
    id: 13,
    title: "photo search",
    category: "react",
    img: "./images/photo-search.png",
    desc: `photo search.`,
  },
  {
    id: 14,
    title: "random person ",
    category: "react",
    img: "./images/random-person.png",
    desc: `random person generator.`,
  },
  {
    id: 15,
    title: "review",
    category: "react",
    img: "./images/review.png",
    desc: `review example.`,
  },
  {
    id: 16,
    title: "slide ",
    category: "react",
    img: "./images/slider.png",
    desc: `slider example.`,
  },
  {
    id: 17,
    title: "stripe",
    category: "react",
    img: "./images/stripe-clone.png",
    desc: `stripe clone.`,
  },
  {
    id: 18,
    title: "tabs",
    category: "react",
    img: "./images/tabs.png",
    desc: `tabs example.`,
  },
  {
    id: 19,
    title: "theme",
    category: "react",
    img: "./images/toggle-theme.png",
    desc: `toggle theme.`,
  },
  {
    id: 20,
    title: "tours",
    category: "react",
    img: "./images/tours-sale.png",
    desc: `tours sale.`,
  },
];

export default projects;